import * as THREE from 'three';
import './style.css';
import { advanceHistory, archaeologyRecover, createHistory, recordDistrictDamage, recordEvent, type CampaignHistory } from './history';
import { simulateDeepTime, type DeepTimeState } from './deepTime';
import { Action, createInputState } from './input';
import { applyStructureImpact, applySupportLoad, createStructureState, type StructureState } from './destruction';
import { applyDamage, type CombatState } from './combat';

type Building = { id: string; mesh: THREE.Mesh; x: number; z: number; width: number; depth: number; height: number; wallRunnable: boolean; climbable: boolean; grapple: boolean; structure: StructureState };
type Scar = { x: number; z: number; year: number; radius: number; mesh: THREE.Mesh };
type WallContact = { building: Building; normal: THREE.Vector3; proximity: number; signedDistance: number; tangentSpeed: number; approachSpeed: number; side: string };
type Debris = { id: string; mesh: THREE.Mesh; velocity: THREE.Vector3; surfable: boolean };
type TraversalState = { wallRun: boolean; wallClimb: boolean; gliding: boolean; diving: boolean; surfing: boolean; rebound: boolean; impactRecovery: boolean; wallContact: boolean; wallSurfaceId: string | null; wallSide: string | null; wallTime: number; grapple: boolean; grappleTarget: boolean };

const input = createInputState();
const scene = new THREE.Scene(); scene.background = new THREE.Color('#09131d'); scene.fog = new THREE.Fog('#09131d', 45, 280);
const camera = new THREE.PerspectiveCamera(60, innerWidth / innerHeight, .1, 520);
const renderer = new THREE.WebGLRenderer({ antialias: true, powerPreference: 'high-performance' }); renderer.setPixelRatio(Math.min(devicePixelRatio, 1.75)); renderer.setSize(innerWidth, innerHeight); renderer.shadowMap.enabled = true; document.querySelector('#app')?.prepend(renderer.domElement);
scene.add(new THREE.HemisphereLight('#c9efff', '#18212b', 1.55)); const sun = new THREE.DirectionalLight('#ffe0a4', 2.2); sun.position.set(-45, 80, 25); sun.castShadow = true; scene.add(sun);
const ground = new THREE.Mesh(new THREE.PlaneGeometry(340, 280), new THREE.MeshStandardMaterial({ color: '#17252d', roughness: .92 })); ground.rotation.x = -Math.PI / 2; ground.receiveShadow = true; scene.add(ground);
const roadMaterial = new THREE.MeshStandardMaterial({ color: '#293b43', roughness: .95 });
for (const z of [-84, 0, 84]) { const road = new THREE.Mesh(new THREE.BoxGeometry(340, .08, 15), roadMaterial); road.position.set(0, .04, z); scene.add(road); }
for (const x of [-100, 0, 100]) { const road = new THREE.Mesh(new THREE.BoxGeometry(15, .08, 280), roadMaterial); road.position.set(x, .05, 0); scene.add(road); }
const buildings: Building[] = []; const rubble: THREE.Mesh[] = []; const colors = ['#557585', '#71838b', '#8a7564', '#526b7a'];
for (let row = -1; row <= 1; row++) for (let col = -2; col <= 2; col++) { if (row === 0 && col === 0) continue; const width = 23 + ((row + col + 8) % 3) * 5, depth = 22 + ((row * 3 + col + 12) % 3) * 4, height = 16 + ((row * 7 + col * 11 + 50) % 5) * 7, x = col * 50, z = row * 70; const mesh = new THREE.Mesh(new THREE.BoxGeometry(width, height, depth), new THREE.MeshStandardMaterial({ color: colors[(row + col + 8) % colors.length], roughness: .76 })); mesh.position.set(x, height / 2, z); mesh.castShadow = true; mesh.receiveShadow = true; scene.add(mesh); const id = `building-${col + 2}-${row + 1}`; buildings.push({ id, mesh, x, z, width, depth, height, wallRunnable: true, climbable: true, grapple: true, structure: createStructureState(id, 100) }); }
const bridge = new THREE.Mesh(new THREE.BoxGeometry(70, 3, 13), new THREE.MeshStandardMaterial({ color: '#bd9861', metalness: .25, roughness: .55 })); bridge.position.set(0, 7, 108); bridge.castShadow = true; scene.add(bridge);
const landmark = new THREE.Mesh(new THREE.CylinderGeometry(10, 13, 28, 8), new THREE.MeshStandardMaterial({ color: '#9ac6cf', emissive: '#143b46', emissiveIntensity: .7 })); landmark.position.set(-100, 14, -112); landmark.castShadow = true; scene.add(landmark);
const debris: Debris[] = [-1, 1].map((direction, index) => { const mesh = new THREE.Mesh(new THREE.BoxGeometry(12, 1.4, 7), new THREE.MeshStandardMaterial({ color: '#a07854', roughness: .82 })); mesh.position.set(direction * 52, 1.2, 45 + index * 18); mesh.castShadow = true; scene.add(mesh); return { id: `debris-${index + 1}`, mesh, velocity: new THREE.Vector3(direction * 9, 0, index ? -4 : 4), surfable: true }; });
const player = new THREE.Mesh(new THREE.CapsuleGeometry(1.1, 2.2, 6, 12), new THREE.MeshStandardMaterial({ color: '#eaf8ff', emissive: '#2e7f99', emissiveIntensity: .8 })); player.position.set(0, 2.2, 35); player.castShadow = true; scene.add(player);
const rival = new THREE.Mesh(new THREE.CapsuleGeometry(1.2, 2.4, 6, 12), new THREE.MeshStandardMaterial({ color: '#ff7187', emissive: '#721d3b', emissiveIntensity: .65 })); rival.position.set(35, 2.4, 12); rival.castShadow = true; scene.add(rival);
const velocity = new THREE.Vector3(); const rivalVelocity = new THREE.Vector3(); const grappleLine = new THREE.Line(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(), new THREE.Vector3()]), new THREE.LineBasicMaterial({ color: '#84e4f3' })); grappleLine.visible = false; scene.add(grappleLine);
const playerCombat: CombatState = { health: 100, maxHealth: 100 };
const traversal: TraversalState = { wallRun: false, wallClimb: false, gliding: false, diving: false, surfing: false, rebound: false, impactRecovery: false, wallContact: false, wallSurfaceId: null, wallSide: null, wallTime: 0, grapple: false, grappleTarget: false };
let started = false, paused = false, dashCooldown = 0, grappleTarget: THREE.Vector3 | null = null, rivalHealth = 100, rivalAttackCooldown = 0, playerHitFlash = 0, attackCooldown = 0, history: CampaignHistory = createHistory(), deepTime: DeepTimeState | null = null, historyViewYear = 0, cameraYaw = 0, cameraPitch = -.2, cameraSensitivity = 1, reducedShake = false, cameraKick = 0, last = performance.now();
const scars: Scar[] = []; const SAVE_KEY = 'immortals-3d-history-v1';
const status = (message: string) => { const el = document.querySelector('#status'); if (el) el.textContent = message; };
const grounded = () => player.position.y <= 2.21;
function createScar(x: number, z: number, year: number, radius = 7): Scar { const mesh = new THREE.Mesh(new THREE.CylinderGeometry(radius, radius * 1.2, .12, 32), new THREE.MeshStandardMaterial({ color: '#10161b', emissive: '#402116', emissiveIntensity: .4 })); mesh.position.set(x, .08, z); scene.add(mesh); return { x, z, year, radius, mesh }; }
function saveState() { localStorage.setItem(SAVE_KEY, JSON.stringify({ history, rivalHealth, player: player.position.toArray(), buildings: buildings.map((b) => ({ height: b.height, visible: b.mesh.visible, integrity: +b.structure.integrity.toFixed(1), support: +b.structure.support.toFixed(2), collapsed: b.structure.collapsed })), scars: scars.map(({ x, z, year, radius }) => ({ x, z, year, radius })) })); status('HISTORY SAVED LOCALLY'); }
function loadState() { try { const saved = JSON.parse(localStorage.getItem(SAVE_KEY) ?? 'null'); if (!saved) return; history = saved.history?.events ? { ...createHistory(), ...saved.history, development: { ...createHistory().development, ...saved.history.development }, relics: saved.history.relics ?? [] } : createHistory(); rivalHealth = Number.isFinite(saved.rivalHealth) ? saved.rivalHealth : 100; if (Array.isArray(saved.player)) player.position.fromArray(saved.player); saved.buildings?.forEach((s: { height?: number; visible?: boolean }, i: number) => { const b = buildings[i]; if (b) { b.height = Number.isFinite(s.height) ? s.height! : b.height; b.mesh.visible = s.visible !== false; b.mesh.scale.y = b.height / (b.mesh.geometry as THREE.BoxGeometry).parameters.height; } }); saved.scars?.forEach((s: { x: number; z: number; year: number; radius?: number }) => scars.push(createScar(s.x, s.z, s.year, s.radius))); } catch { localStorage.removeItem(SAVE_KEY); } }
function findWall(): WallContact | null { let best: WallContact | null = null; const search = 1.65 + Math.min(3.2, velocity.clone().setY(0).length() * .045); for (const b of buildings) { if (!b.mesh.visible || player.position.y > b.height + 1.5) continue; const minX = b.x - b.width / 2, maxX = b.x + b.width / 2, minZ = b.z - b.depth / 2, maxZ = b.z + b.depth / 2; const cs = [{ d: minX - player.position.x, n: new THREE.Vector3(-1, 0, 0), side: 'left', valid: player.position.z >= minZ - search && player.position.z <= maxZ + search }, { d: player.position.x - maxX, n: new THREE.Vector3(1, 0, 0), side: 'right', valid: player.position.z >= minZ - search && player.position.z <= maxZ + search }, { d: minZ - player.position.z, n: new THREE.Vector3(0, 0, -1), side: 'front', valid: player.position.x >= minX - search && player.position.x <= maxX + search }, { d: player.position.z - maxZ, n: new THREE.Vector3(0, 0, 1), side: 'back', valid: player.position.x >= minX - search && player.position.x <= maxX + search }].filter((v) => v.valid && Math.abs(v.d) <= search).sort((a, z) => Math.abs(a.d) - Math.abs(z.d)); const c = cs[0]; if (!c) continue; const normalVelocity = velocity.dot(c.n); const tangent = velocity.clone().addScaledVector(c.n, -normalVelocity).setY(0).length(); const result = { building: b, normal: c.n, proximity: Math.abs(c.d), signedDistance: c.d, tangentSpeed: tangent, approachSpeed: Math.max(0, -normalVelocity), side: c.side }; if (!best || result.proximity < best.proximity) best = result; } return best; }
function resolveWall(wall: WallContact | null) { if (!wall || wall.signedDistance >= 1.2) return; player.position.addScaledVector(wall.normal, 1.2 - wall.signedDistance); const inward = velocity.dot(wall.normal); if (inward < 0) velocity.addScaledVector(wall.normal, -inward); }
function findGrapple() { const view = new THREE.Vector3(Math.sin(cameraYaw), 0, -Math.cos(cameraYaw)); let best: THREE.Vector3 | null = null; let score = .82; for (const b of buildings) { if (!b.mesh.visible || !b.grapple) continue; const target = new THREE.Vector3(b.x, Math.min(b.height - 1, 32), b.z); const delta = target.clone().sub(player.position); const distance = delta.length(); if (distance > 78) continue; const alignment = view.dot(delta.normalize()); if (alignment < score) continue; const ray = new THREE.Raycaster(player.position, target.clone().sub(player.position).normalize(), 0, distance); if (ray.intersectObjects(buildings.filter((v) => v !== b && v.mesh.visible).map((v) => v.mesh)).length) continue; score = alignment; best = target; } return best; }
function nearestDebris() { return debris.reduce<Debris | null>((best, item) => Math.hypot(item.mesh.position.x - player.position.x, item.mesh.position.z - player.position.z) < (best ? Math.hypot(best.mesh.position.x - player.position.x, best.mesh.position.z - player.position.z) : 9) ? item : best, null); }
function updateCamera(dt: number) { const speed = velocity.clone().setY(0).length(); const high = THREE.MathUtils.clamp(speed / 65, 0, 1); camera.fov = THREE.MathUtils.lerp(camera.fov, 60 + high * 8, 1 - Math.pow(.0005, dt)); camera.updateProjectionMatrix(); const distance = 19 + high * 7; const offset = new THREE.Vector3(Math.sin(cameraYaw) * distance, 9 + player.position.y * .12 - cameraPitch * 5, Math.cos(cameraYaw) * distance); const desired = player.position.clone().add(offset); const ray = new THREE.Raycaster(player.position.clone().add(new THREE.Vector3(0, 2, 0)), offset.clone().normalize(), 0, distance); const hit = ray.intersectObjects(buildings.filter((b) => b.mesh.visible).map((b) => b.mesh))[0]; if (hit) desired.copy(ray.ray.origin).add(offset.normalize().multiplyScalar(Math.max(4.5, hit.distance - 1.5))); camera.position.lerp(desired, 1 - Math.pow(.0008, dt)); if (!reducedShake && cameraKick) camera.position.y += Math.sin(performance.now() * .05) * cameraKick; camera.lookAt(player.position.x, player.position.y + 2.1, player.position.z); cameraKick = Math.max(0, cameraKick - dt * 4); }
function hud() { const set = (id: string, value: string) => { const el = document.querySelector(`#${id}`); if (el) el.textContent = value; }; set('year', String(history.year)); set('district', player.position.x < 0 ? 'WESTERN QUARTER' : 'EASTERN QUARTER'); set('velocity', String(Math.round(velocity.length()))); set('rival', String(rivalHealth)); set('vitality', String(Math.round(playerCombat.health))); set('state', traversal.wallRun ? 'WALL RUN' : traversal.wallClimb ? 'WALL CLIMB' : traversal.grapple ? 'GRAPPLE' : traversal.gliding ? 'GLIDE' : traversal.diving ? 'DIVE' : traversal.surfing ? 'SURF' : traversal.impactRecovery ? 'RECOVERY' : 'GROUND'); }
function collapseBuilding(b: Building) { if (!b.mesh.visible) return false; b.mesh.visible = false; b.height = 0; b.mesh.scale.y = .08; spawnRubble(b); recordEvent(history, { year: history.year, type: 'collapse', siteId: b.id, consequence: 'A structure collapses and becomes an inherited ruin.', publicAccount: 'The collapse is attributed to an old construction fault.', evidenceStrength: .45 }); return true; }
function shockwave() { const scar = createScar(player.position.x, player.position.z, history.year); scars.push(scar); recordDistrictDamage(history, player.position.x); recordEvent(history, { year: history.year, type: 'collapse', siteId: `scar-${scars.length}`, consequence: 'A terrain scar becomes a permanent geographic reference.', publicAccount: 'Later maps call the depression natural.', evidenceStrength: .7 }); const collapsed: Building[] = []; for (const b of buildings) if (b.mesh.visible && Math.hypot(b.x - player.position.x, b.z - player.position.z) < 18) { const impact = applyStructureImpact(b.structure, 28); b.height = Math.max(0, b.height - 12); b.mesh.scale.y = Math.max(.08, b.height / (b.mesh.geometry as THREE.BoxGeometry).parameters.height); if ((impact.collapsed || !b.height) && collapseBuilding(b)) collapsed.push(b); } for (const source of collapsed) for (const neighbor of buildings) if (neighbor !== source && neighbor.mesh.visible && Math.hypot(neighbor.x - source.x, neighbor.z - source.z) < 56) { const load = applySupportLoad(neighbor.structure, 18); neighbor.height = Math.max(0, neighbor.height - 5); neighbor.mesh.scale.y = Math.max(.08, neighbor.height / (neighbor.mesh.geometry as THREE.BoxGeometry).parameters.height); if (load.collapsed && collapseBuilding(neighbor)) recordEvent(history, { year: history.year, type: 'collapse', siteId: `${neighbor.id}-support`, consequence: 'A neighboring structure fails after inherited support load.', publicAccount: 'The second collapse is recorded as unrelated damage.', evidenceStrength: .4 }); } saveState(); status(collapsed.length ? 'SHOCKWAVE // SUPPORT LOAD PROPAGATED' : 'SHOCKWAVE // TERRAIN SCAR RECORDED'); }
function update(dt: number) { if (!started || paused) return; const move = new THREE.Vector3(Number(input.down.has(Action.MoveRight)) - Number(input.down.has(Action.MoveLeft)), 0, Number(input.down.has(Action.MoveBack)) - Number(input.down.has(Action.MoveForward))); if (move.lengthSq()) move.normalize(); const forward = new THREE.Vector3(Math.sin(cameraYaw), 0, -Math.cos(cameraYaw)); const right = new THREE.Vector3(Math.cos(cameraYaw), 0, Math.sin(cameraYaw)); const wish = forward.multiplyScalar(-move.z).add(right.multiplyScalar(move.x)); if (wish.lengthSq()) wish.normalize(); const sprint = input.down.has(Action.Sprint); const maxSpeed = sprint ? 66 : 27; const accel = grounded() ? sprint ? 150 : 100 : 52; if (wish.lengthSq()) velocity.addScaledVector(wish, accel * dt); const horizontal = velocity.clone().setY(0); if (horizontal.length() > maxSpeed) { const y = velocity.y; velocity.copy(horizontal.normalize().multiplyScalar(maxSpeed)); velocity.y = y; } const drag = grounded() ? wish.lengthSq() ? .96 : .82 : .995; velocity.x *= Math.pow(drag, dt * 60); velocity.z *= Math.pow(drag, dt * 60);
  const wall = findWall(); traversal.wallContact = !!wall; traversal.wallSurfaceId = wall?.building.id ?? null; traversal.wallSide = wall?.side ?? null; traversal.wallRun = traversal.wallClimb = traversal.gliding = traversal.diving = traversal.rebound = false;
  if (input.pressed.has(Action.Jump) && grounded()) { velocity.y = sprint ? 28 : 23; status('LONG JUMP // MOMENTUM CARRIED'); }
  if (input.pressed.has(Action.Jump) && !grounded() && wall && wall.tangentSpeed > 10 && wall.approachSpeed < 10) { velocity.addScaledVector(wall.normal, 24); velocity.y = 19; traversal.rebound = true; status('REBOUND // WALL EXIT'); }
  if (!grounded() && wall && input.down.has(Action.Jump) && wall.building.climbable && wish.dot(wall.normal) < -.25) { traversal.wallClimb = true; velocity.y = Math.max(velocity.y, 14); status('WALL CLIMB // CONTACT LOCKED'); } else if (!grounded() && wall && input.down.has(Action.Jump) && wall.tangentSpeed > 10) { traversal.wallRun = true; traversal.wallTime += dt; velocity.y = Math.max(velocity.y, 3.5); velocity.addScaledVector(wall.normal, -velocity.dot(wall.normal)); status('WALL RUN // CONTACT LOCKED'); } else traversal.wallTime = Math.max(0, traversal.wallTime - dt * 2);
  if (!grounded() && input.down.has(Action.Glide) && !traversal.wallClimb && !traversal.diving) { traversal.gliding = true; velocity.y = Math.max(velocity.y - 9 * dt, -6); if (wish.lengthSq()) velocity.addScaledVector(wish, 26 * dt); }
  if (!grounded() && input.down.has(Action.Dive)) { traversal.diving = true; traversal.gliding = false; velocity.y = Math.max(-78, velocity.y - 105 * dt); if (wish.lengthSq()) velocity.addScaledVector(wish, 18 * dt); }
  const ride = nearestDebris(); if (input.down.has(Action.Surf) && grounded() && ride && Math.hypot(ride.mesh.position.x - player.position.x, ride.mesh.position.z - player.position.z) < 8) { traversal.surfing = true; velocity.x = ride.velocity.x; velocity.z = ride.velocity.z; status('DEBRIS SURF // RIDING'); } if (!input.down.has(Action.Surf)) traversal.surfing = false;
  if (input.pressed.has(Action.Dash) && dashCooldown <= 0) { velocity.add(wish.lengthSq() ? wish.multiplyScalar(42) : forward.multiplyScalar(42)); dashCooldown = .72; status('AIR DASH // MOMENTUM PRESERVED'); } dashCooldown = Math.max(0, dashCooldown - dt); attackCooldown = Math.max(0, attackCooldown - dt); rivalAttackCooldown = Math.max(0, rivalAttackCooldown - dt); playerHitFlash = Math.max(0, playerHitFlash - dt);
  if (input.pressed.has(Action.Grapple)) { grappleTarget = findGrapple(); if (grappleTarget) { grappleLine.visible = true; status('GRAPPLE LOCKED // HOLD E TO SWING'); } else status('NO VALID GRAPPLE ANCHOR'); } traversal.grapple = traversal.grappleTarget = !!grappleTarget; if (grappleTarget && input.down.has(Action.Grapple)) { const pull = grappleTarget.clone().sub(player.position); velocity.addScaledVector(pull.normalize(), (pull.length() > 18 ? 58 : 30) * dt); grappleLine.geometry.setFromPoints([player.position, grappleTarget]); } else if (!input.down.has(Action.Grapple)) { grappleTarget = null; grappleLine.visible = false; }
  if (input.pressed.has(Action.Shockwave)) { velocity.y = 18; cameraKick = 1.2; shockwave(); }
  if (input.pressed.has(Action.Attack) && attackCooldown <= 0 && player.position.distanceTo(rival.position) < 14 && rivalHealth > 0) { const hit = applyDamage({ health: rivalHealth, maxHealth: 100 }, 25); rivalHealth = hit.remaining; attackCooldown = .35; if (!hit.defeated) rivalVelocity.add(player.position.clone().sub(rival.position).normalize().multiplyScalar(-18)); recordEvent(history, { year: history.year, type: 'strike', siteId: 'rival-impact-zone', consequence: hit.defeated ? 'The rival falls and the battle is won.' : 'The rival is driven back through the city.', publicAccount: 'Witnesses disagree about who started the fight.', evidenceStrength: .55 }); if (hit.defeated) { rival.visible = false; saveState(); } status(hit.defeated ? 'RIVAL DOWN // BATTLE WON' : 'STRIKE // RIVAL STAGGERED'); }
  if (input.pressed.has(Action.Century) && rivalHealth <= 0) { advanceHistory(history); rivalHealth = 100; rival.visible = true; rival.position.copy(player.position).add(new THREE.Vector3(28, 0, -24)); saveState(); status(`YEAR ${history.year} // THE CITY REMEMBERS`); } if (input.pressed.has(Action.Save)) saveState(); if (input.pressed.has(Action.Archaeology)) { const event = history.events.find((v) => v.evidenceStrength < .35); if (event) { archaeologyRecover(history, event.id); saveState(); status('ARCHAEOLOGY // OBJECTIVE HISTORY RECOVERED'); } } if (input.pressed.has(Action.DeepTime)) { deepTime = simulateDeepTime(1701); status('DEEP TIME // YEAR 100,000 REACHED'); }
  velocity.y -= (traversal.wallRun ? 8 : traversal.wallClimb ? 2 : traversal.gliding ? 6 : 42) * dt; player.position.addScaledVector(velocity, dt); if (traversal.surfing && ride) { player.position.addScaledVector(ride.velocity, dt); player.position.y = Math.max(player.position.y, ride.mesh.position.y + 2.2); } player.position.y = Math.max(2.2, player.position.y); if (grounded()) { if (velocity.y < -24) { traversal.impactRecovery = true; velocity.multiply(new THREE.Vector3(.55, 0, .55)); status('HARD LANDING // IMPACT RECOVERY'); } else traversal.impactRecovery = false; velocity.y = Math.max(0, velocity.y); } player.position.x = THREE.MathUtils.clamp(player.position.x, -158, 158); player.position.z = THREE.MathUtils.clamp(player.position.z, -128, 128); if (rivalHealth > 0) { const toPlayer = player.position.clone().sub(rival.position); if (toPlayer.length() > 7) rivalVelocity.add(toPlayer.normalize().multiplyScalar(4 * dt)); rivalVelocity.multiplyScalar(Math.pow(.02, dt)); rival.position.addScaledVector(rivalVelocity, dt); rival.position.y = 2.4; } else rival.visible = false; if (rivalHealth > 0 && player.position.distanceTo(rival.position) < 7 && rivalAttackCooldown <= 0) { const hit = applyDamage(playerCombat, 8); rivalAttackCooldown = 1.1; playerHitFlash = .22; cameraKick = Math.max(cameraKick, .45); status("RIVAL STRIKE // PLAYER HIT"); } if (playerCombat.health <= 0) { playerCombat.health = playerCombat.maxHealth; player.position.set(0, 2.2, 35); velocity.set(0, 0, 0); status("RECOVERED // IMMORTAL BODY RESTORED"); } resolveWall(wall); hud(); }
function spawnRubble(b: Building) { for (let i = 0; i < 4; i += 1) { const chunk = new THREE.Mesh(new THREE.BoxGeometry(3 + i, 1.2 + i * .3, 2.5), new THREE.MeshStandardMaterial({ color: '#765c49', roughness: .95 })); chunk.position.set(b.x + (i - 1.5) * 3, .7 + i * .25, b.z + (i % 2 ? 3 : -3)); chunk.rotation.y = i * .7; chunk.castShadow = true; scene.add(chunk); rubble.push(chunk); } }
function frame(now: number) { const dt = Math.min(.05, (now - last) / 1000); last = now; update(dt); for (const d of debris) { d.mesh.position.addScaledVector(d.velocity, dt); if (Math.abs(d.mesh.position.x) > 125) d.velocity.x *= -1; if (Math.abs(d.mesh.position.z) > 115) d.velocity.z *= -1; } updateCamera(dt); renderer.render(scene, camera); input.consumeFrame(); requestAnimationFrame(frame); }
addEventListener('keydown', (event) => { const key = event.key === ' ' ? 'space' : event.key.toLowerCase(); if (['space', 'arrowup', 'arrowdown', 'arrowleft', 'arrowright'].includes(key)) event.preventDefault(); input.keyDown(key); if (input.pressed.has(Action.Pause) && started) { paused = !paused; document.querySelector('#pause')?.classList.toggle('hidden', !paused); if (paused && document.pointerLockElement) document.exitPointerLock(); } if (input.pressed.has(Action.CameraFaster)) cameraSensitivity = Math.min(2, cameraSensitivity + .1); if (input.pressed.has(Action.CameraSlower)) cameraSensitivity = Math.max(.5, cameraSensitivity - .1); if (input.pressed.has(Action.ReducedShake)) reducedShake = !reducedShake; });
addEventListener('keyup', (event) => input.keyUp(event.key === ' ' ? 'space' : event.key)); renderer.domElement.addEventListener('click', () => { if (started && !paused) renderer.domElement.requestPointerLock?.(); }); addEventListener('mousemove', (event) => { if (document.pointerLockElement === renderer.domElement && started && !paused) { cameraYaw -= event.movementX * .0025 * cameraSensitivity; cameraPitch = THREE.MathUtils.clamp(cameraPitch - event.movementY * .0022 * cameraSensitivity, -.9, .65); } }); addEventListener('resize', () => { camera.aspect = innerWidth / innerHeight; camera.updateProjectionMatrix(); renderer.setSize(innerWidth, innerHeight); });
document.querySelector('#enter')?.addEventListener('click', () => { loadState(); started = true; document.querySelector('#title')?.classList.add('hidden'); document.querySelector('#hud')?.classList.remove('hidden'); document.querySelector('#help')?.classList.remove('hidden'); status('TRAVERSAL ONLINE // POINTER LOCK READY'); });
document.querySelector('#timeline')?.addEventListener('input', (event) => { historyViewYear = Number((event.target as HTMLInputElement).value); const output = document.querySelector('#timeline-year'); if (output) output.textContent = String(historyViewYear); });
window.render_game_to_text = () => JSON.stringify({ coordinateSystem: 'Three.js world: x east, y up, z south', mode: paused ? 'paused' : started ? 'explore' : 'title', year: history.year, player: { x: +player.position.x.toFixed(2), y: +player.position.y.toFixed(2), z: +player.position.z.toFixed(2), vx: +velocity.x.toFixed(2), vy: +velocity.y.toFixed(2), vz: +velocity.z.toFixed(2) }, rival: { health: rivalHealth, visible: rival.visible, attackCooldown: +rivalAttackCooldown.toFixed(2) }, playerCombat: { health: playerCombat.health, hitFlash: +playerHitFlash.toFixed(2), attackCooldown: +attackCooldown.toFixed(2) }, history: history.events.slice(-12), historyViewYear, deepTime, scars: scars.map(({ x, z, year, radius }) => ({ x, z, year, radius })), traversal: { ...traversal, wallTime: +traversal.wallTime.toFixed(2), dashCooldown: +dashCooldown.toFixed(2), cameraYaw: +cameraYaw.toFixed(2), cameraPitch: +cameraPitch.toFixed(2), cameraSensitivity, reducedShake, debris: debris.map((d) => ({ id: d.id, x: +d.mesh.position.x.toFixed(1), z: +d.mesh.position.z.toFixed(1) })) }, performance: { pixelRatio: renderer.getPixelRatio(), drawCalls: renderer.info.render.calls }, buildings: buildings.map((b) => ({ id: b.id, x: b.x, z: b.z, height: b.height, visible: b.mesh.visible, integrity: +b.structure.integrity.toFixed(1), support: +b.structure.support.toFixed(2), collapsed: b.structure.collapsed })), rubbleCount: rubble.length });
window.advanceTime = (ms: number) => { const steps = Math.max(1, Math.round(ms / (1000 / 60))); for (let i = 0; i < steps; i += 1) { update(1 / 60); input.consumeFrame(); } renderer.render(scene, camera); };
camera.position.set(0, 17, 62); camera.lookAt(player.position.x, player.position.y + 2, player.position.z); requestAnimationFrame(frame);
