import * as THREE from 'three';
import './style.css';
import { advanceHistory, createHistory, recordDistrictDamage, recordEvent, type CampaignHistory } from './history';

type Building = { mesh: THREE.Mesh; x: number; z: number; width: number; depth: number; height: number };
type Scar = { x: number; z: number; year: number; radius: number; mesh: THREE.Mesh };
const input = { down: new Set<string>(), pressed: new Set<string>() };
const scene = new THREE.Scene(); scene.background = new THREE.Color('#0a1119'); scene.fog = new THREE.Fog('#0a1119', 40, 260);
const camera = new THREE.PerspectiveCamera(58, innerWidth / innerHeight, .1, 500);
const renderer = new THREE.WebGLRenderer({ antialias: true, powerPreference: 'high-performance' }); renderer.setPixelRatio(Math.min(devicePixelRatio, 2)); renderer.setSize(innerWidth, innerHeight); renderer.shadowMap.enabled = true; document.querySelector('#app')?.prepend(renderer.domElement);
scene.add(new THREE.HemisphereLight('#c9efff', '#18212b', 1.6)); const sun = new THREE.DirectionalLight('#ffe0a4', 2.2); sun.position.set(-45, 80, 25); sun.castShadow = true; scene.add(sun);
const ground = new THREE.Mesh(new THREE.PlaneGeometry(320, 260), new THREE.MeshStandardMaterial({ color: '#18232b', roughness: .9 })); ground.rotation.x = -Math.PI / 2; ground.receiveShadow = true; scene.add(ground);
const roadMaterial = new THREE.MeshStandardMaterial({ color: '#26343b', roughness: .95 });
for (const z of [-70, 0, 70]) { const road = new THREE.Mesh(new THREE.BoxGeometry(320, .08, 16), roadMaterial); road.position.set(0, .04, z); scene.add(road); }
for (const x of [-90, 0, 90]) { const road = new THREE.Mesh(new THREE.BoxGeometry(16, .08, 260), roadMaterial); road.position.set(x, .05, 0); scene.add(road); }
const buildings: Building[] = []; const buildingColors = ['#516979', '#6d7d85', '#806f61', '#4f6270'];
const scars: Scar[] = [];
const shelters: THREE.Mesh[] = [];
for (let row = -1; row <= 1; row++) for (let col = -2; col <= 2; col++) { if (row === 0 && col === 0) continue; const width = 22 + ((row + col + 8) % 3) * 5, depth = 20 + ((row * 3 + col + 12) % 3) * 4, height = 12 + ((row * 7 + col * 11 + 50) % 5) * 7, x = col * 50, z = row * 70; const mesh = new THREE.Mesh(new THREE.BoxGeometry(width, height, depth), new THREE.MeshStandardMaterial({ color: buildingColors[(row + col + 8) % buildingColors.length], roughness: .76 })); mesh.position.set(x, height / 2, z); mesh.castShadow = true; mesh.receiveShadow = true; scene.add(mesh); buildings.push({ mesh, x, z, width, depth, height }); }
const bridge = new THREE.Mesh(new THREE.BoxGeometry(66, 3, 12), new THREE.MeshStandardMaterial({ color: '#bd9861', metalness: .25, roughness: .55 })); bridge.position.set(0, 7, 104); bridge.castShadow = true; scene.add(bridge);
const landmark = new THREE.Mesh(new THREE.CylinderGeometry(10, 13, 28, 8), new THREE.MeshStandardMaterial({ color: '#9ac6cf', emissive: '#143b46', emissiveIntensity: .7 })); landmark.position.set(-90, 14, -105); landmark.castShadow = true; scene.add(landmark);
const player = new THREE.Mesh(new THREE.CapsuleGeometry(1.1, 2.2, 6, 12), new THREE.MeshStandardMaterial({ color: '#eaf8ff', emissive: '#2e7f99', emissiveIntensity: .8 })); player.position.set(0, 2.2, 35); player.castShadow = true; scene.add(player);
const rival = new THREE.Mesh(new THREE.CapsuleGeometry(1.2, 2.4, 6, 12), new THREE.MeshStandardMaterial({ color: '#ff7187', emissive: '#721d3b', emissiveIntensity: .65 })); rival.position.set(35, 2.4, 12); rival.castShadow = true; scene.add(rival);
const velocity = new THREE.Vector3(); const grappleLine = new THREE.Line(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(), new THREE.Vector3()]), new THREE.LineBasicMaterial({ color: '#84e4f3' })); grappleLine.visible = false; scene.add(grappleLine);
let started = false, paused = false, wallRun = false, dashTimer = 0, grappleTarget: THREE.Vector3 | null = null, rivalHealth = 100, rivalVelocity = new THREE.Vector3(), history: CampaignHistory = createHistory(), last = performance.now();
const SAVE_KEY = 'immortals-3d-history-v1';
function saveState() { localStorage.setItem(SAVE_KEY, JSON.stringify({ history, rivalHealth, player: player.position.toArray(), buildings: buildings.map((b) => ({ height: b.height, visible: b.mesh.visible })), scars: scars.map(({ x, z, year: scarYear, radius }) => ({ x, z, year: scarYear, radius })) })); showStatus('HISTORY SAVED LOCALLY'); }
function createScar(x: number, z: number, scarYear: number, radius = 7) { const mesh = new THREE.Mesh(new THREE.CylinderGeometry(radius, radius * 1.2, .12, 32), new THREE.MeshStandardMaterial({ color: '#10161b', emissive: '#402116', emissiveIntensity: .4 })); mesh.position.set(x, .08, z); scene.add(mesh); const scar = { x, z, year: scarYear, radius, mesh }; scars.push(scar); return scar; }
function applyDevelopmentVisuals() { const reinforcement = history.development.adaptation / 100; buildings.forEach((building) => { const material = building.mesh.material as THREE.MeshStandardMaterial; material.color.lerp(new THREE.Color(building.x < 0 ? '#6fabbc' : '#b19a70'), reinforcement * .65); material.roughness = Math.max(.35, .76 - reinforcement * .3); }); const targetShelters = Math.min(5, Math.floor(history.development.sheltering / 20)); while (shelters.length < targetShelters) { const index = shelters.length, mesh = new THREE.Mesh(new THREE.BoxGeometry(8, 2.5, 8), new THREE.MeshStandardMaterial({ color: '#9ba9a0', metalness: .15, roughness: .5 })); mesh.position.set(-110 + index * 55, 1.25, index % 2 ? -24 : 24); mesh.castShadow = true; scene.add(mesh); shelters.push(mesh); } }
function loadState() { try { const saved = JSON.parse(localStorage.getItem(SAVE_KEY) ?? 'null'); if (!saved) return; history = saved.history?.events ? { ...createHistory(), ...saved.history, development: { ...createHistory().development, ...saved.history.development } } : createHistory(); rivalHealth = Number.isFinite(saved.rivalHealth) ? saved.rivalHealth : 100; if (Array.isArray(saved.player)) player.position.fromArray(saved.player); saved.buildings?.forEach((state: { height?: number; visible?: boolean }, index: number) => { const building = buildings[index]; if (building) { building.height = Number.isFinite(state.height) ? state.height : building.height; building.mesh.visible = state.visible !== false; building.mesh.scale.y = building.height / (building.mesh.geometry as THREE.BoxGeometry).parameters.height; } }); saved.scars?.forEach((scar: { x: number; z: number; year: number; radius?: number }) => createScar(scar.x, scar.z, scar.year, scar.radius)); applyDevelopmentVisuals(); } catch { localStorage.removeItem(SAVE_KEY); } }
function advanceCentury() { if (history.year < 100000) { advanceHistory(history); applyDevelopmentVisuals(); rivalHealth = 100; rival.visible = true; rival.position.set(player.position.x + 28, 2.4, player.position.z - 24); showStatus(`YEAR ${history.year} // ${shelters.length} SHELTERS // THE CITY REMEMBERS`); saveState(); } }
function nearestBuilding(): THREE.Vector3 | null { let best: Building | undefined; let distance = 38; for (const building of buildings) { const d = Math.hypot(building.x - player.position.x, building.z - player.position.z); if (d < distance) { distance = d; best = building; } } return best ? new THREE.Vector3(best.x, Math.min(best.height - 1, 28), best.z) : null; }
function showStatus(message: string) { const el = document.querySelector('#status'); if (el) el.textContent = message; }
function update(dt: number) {
  if (!started || paused) return; const left = input.down.has('a') || input.down.has('arrowleft'), right = input.down.has('d') || input.down.has('arrowright'), forward = input.down.has('w') || input.down.has('arrowup'), back = input.down.has('s') || input.down.has('arrowdown'); const direction = new THREE.Vector3(Number(right) - Number(left), 0, Number(back) - Number(forward)); if (direction.lengthSq()) direction.normalize(); const sprint = input.down.has('shift'), speed = sprint ? 30 : 16;
  velocity.x += direction.x * speed * 7 * dt; velocity.z += direction.z * speed * 7 * dt; velocity.x *= Math.pow(.0008, dt); velocity.z *= Math.pow(.0008, dt);
  if (input.pressed.has('space') && player.position.y <= 2.21) velocity.y = 19; wallRun = false; if (input.down.has('space') && player.position.y > 2.3 && Math.abs(velocity.x) + Math.abs(velocity.z) > 8) { velocity.y = Math.max(velocity.y, 5); wallRun = true; }
  if (input.pressed.has('q') && dashTimer <= 0) { velocity.add(direction.lengthSq() ? direction.multiplyScalar(34) : new THREE.Vector3(0, 0, -34)); dashTimer = .65; showStatus('AIR DASH // MOMENTUM'); } dashTimer -= dt;
  if (input.pressed.has('e')) { grappleTarget = nearestBuilding(); if (grappleTarget) { grappleLine.visible = true; showStatus('GRAPPLE LOCKED'); } } if (grappleTarget && input.down.has('e')) { const pull = grappleTarget.clone().sub(player.position); velocity.add(pull.normalize().multiplyScalar(30 * dt)); grappleLine.geometry.setFromPoints([player.position, grappleTarget]); } if (!input.down.has('e')) { grappleTarget = null; grappleLine.visible = false; }
  if (input.pressed.has('f') && player.position.distanceTo(rival.position) < 10 && rivalHealth > 0) { rivalHealth = Math.max(0, rivalHealth - 25); rivalVelocity.add(player.position.clone().sub(rival.position).normalize().multiplyScalar(-18)); recordEvent(history, { year: history.year, type: 'strike', siteId: 'rival-impact-zone', consequence: 'The rival is driven back through the city.' }); showStatus(rivalHealth ? 'STRIKE // RIVAL STAGGERED' : 'RIVAL DOWN // BATTLE WON'); }
  if (input.pressed.has('r')) { velocity.y = 16; createScar(player.position.x, player.position.z, history.year); recordDistrictDamage(history, player.position.x); recordEvent(history, { year: history.year, type: 'collapse', siteId: `scar-${scars.length}`, consequence: 'A terrain scar becomes a permanent geographic reference.' }); showStatus('SHOCKWAVE // TERRAIN SCAR RECORDED'); for (const building of buildings) { if (player.position.distanceTo(building.mesh.position) < 18) { building.height = Math.max(0, building.height - 12); building.mesh.scale.y = Math.max(.08, building.height / (building.mesh.geometry as THREE.BoxGeometry).parameters.height); if (!building.height) { building.mesh.visible = false; recordEvent(history, { year: history.year, type: 'collapse', siteId: `building-${building.x}-${building.z}`, consequence: 'A structure collapses and becomes an inherited ruin.' }); showStatus('STRUCTURE COLLAPSED // RUBBLE REMAINS'); } } } applyDevelopmentVisuals(); saveState(); } if (input.pressed.has('c') && rivalHealth <= 0) advanceCentury(); if (input.pressed.has('k')) saveState(); if (input.pressed.has('h')) { const panel = document.querySelector('#history'); panel?.classList.toggle('hidden'); const list = document.querySelector('#history-list'); if (list) list.innerHTML = history.events.slice(-12).reverse().map((event) => `<div class="history-event"><b>YEAR ${event.year} · ${event.type.toUpperCase()}</b><br>${event.siteId}: ${event.consequence}</div>`).join('') || 'No recorded consequences yet.'; } velocity.y -= (wallRun ? 9 : 42) * dt; player.position.addScaledVector(velocity, dt); player.position.y = Math.max(2.2, player.position.y); if (player.position.y === 2.2) velocity.y = Math.max(0, velocity.y); player.position.x = THREE.MathUtils.clamp(player.position.x, -148, 148); player.position.z = THREE.MathUtils.clamp(player.position.z, -118, 118);
  if (rivalHealth > 0) { const toPlayer = player.position.clone().sub(rival.position); if (toPlayer.length() > 7) rivalVelocity.add(toPlayer.normalize().multiplyScalar(4 * dt)); rivalVelocity.multiplyScalar(Math.pow(.02, dt)); rival.position.addScaledVector(rivalVelocity, dt); rival.position.y = 2.4; } else rival.visible = false;
  const desired = player.position.clone().add(new THREE.Vector3(0, 15, 27)); camera.position.lerp(desired, 1 - Math.pow(.0008, dt)); camera.lookAt(player.position.x, player.position.y + 2, player.position.z); const yearReadout = document.querySelector('#year'); if (yearReadout) yearReadout.textContent = String(history.year); const district = document.querySelector('#district'); if (district) district.textContent = player.position.x < 0 ? 'WESTERN QUARTER' : 'EASTERN QUARTER'; const speedReadout = document.querySelector('#velocity'); if (speedReadout) speedReadout.textContent = String(Math.round(velocity.length())); const adaptation = document.querySelector('#adaptation'); if (adaptation) adaptation.textContent = String(Math.round(history.development.adaptation)); const rivalReadout = document.querySelector('#rival'); if (rivalReadout) rivalReadout.textContent = String(rivalHealth); input.pressed.clear();
}
function frame(now: number) { const dt = Math.min(.05, (now - last) / 1000); last = now; update(dt); renderer.render(scene, camera); requestAnimationFrame(frame); }
addEventListener('keydown', (event) => { const key = event.key.toLowerCase(); if ([' ', 'arrowup', 'arrowdown', 'arrowleft', 'arrowright'].includes(key)) event.preventDefault(); if (!input.down.has(key)) input.pressed.add(key); input.down.add(key); if (key === 'escape' && started) { paused = !paused; document.querySelector('#pause')?.classList.toggle('hidden', !paused); } }); addEventListener('keyup', (event) => input.down.delete(event.key.toLowerCase())); addEventListener('resize', () => { camera.aspect = innerWidth / innerHeight; camera.updateProjectionMatrix(); renderer.setSize(innerWidth, innerHeight); });
document.querySelector('#enter')?.addEventListener('click', () => { loadState(); started = true; document.querySelector('#title')?.classList.add('hidden'); document.querySelector('#hud')?.classList.remove('hidden'); document.querySelector('#help')?.classList.remove('hidden'); showStatus(history.year ? `YEAR ${history.year} // RETURNED TO THE CITY` : 'TRAVERSAL ONLINE'); }); camera.position.set(0, 17, 62); camera.lookAt(player.position);
window.render_game_to_text = () => JSON.stringify({ coordinateSystem: 'Three.js world: x east, y up, z south', mode: paused ? 'paused' : started ? 'explore' : 'title', year: history.year, development: history.development, player: { x: +player.position.x.toFixed(2), y: +player.position.y.toFixed(2), z: +player.position.z.toFixed(2), vx: +velocity.x.toFixed(2), vy: +velocity.y.toFixed(2), vz: +velocity.z.toFixed(2) }, rival: { x: +rival.position.x.toFixed(2), z: +rival.position.z.toFixed(2), health: rivalHealth }, history: history.events.slice(-12), scars: scars.map(({ x, z, year: scarYear, radius }) => ({ x, z, year: scarYear, radius })), wallRun, grapple: !!grappleTarget, dashCooldown: Math.max(0, +dashTimer.toFixed(2)), buildings: buildings.map((b) => ({ x: b.x, z: b.z, height: b.height, visible: b.mesh.visible })) });
window.advanceTime = (ms: number) => { const steps = Math.max(1, Math.round(ms / (1000 / 60))); for (let i = 0; i < steps; i += 1) update(1 / 60); renderer.render(scene, camera); }; requestAnimationFrame(frame);
